### ISSUE TITLE
3ds crashes when you try to close Flappy Bird via home button and close

### ISSUE THREAD

**Issue by 99powerbreaker** [NPI-D7/Flappy-Bird#1]
Steps to reproduce: 
1. Open the game
2. When game opens, press the home button.
3. Press the Close option.
4. The game Crashes

Yes I am aware that you can exit by pressing start, but I thought that this still should be brought up

https://user-images.githubusercontent.com/99379078/162645580-f7b9e309-3a26-45ce-a11b-6add05560c59.mp4

**Comment by tobid7** [comment]
Thank you for your bug report.
I'll tested it and it sometimes crashes and sometimes not lol.
I'll fix that later.

**Comment by tobid7** [comment]
Fixed at: 
https://github.com/NPI-D7/Flappy-Bird/actions/runs/2147116605
